baseurl = "https://blog.viacodigo.com/"

theme = "ghostwriter"

copyright = "Vía Código"
googleAnalytics = "UA-56029240-5"
disqusShortname = "viacodigo-blog"

DefaultContentLanguage = "es"
[languages]
  [languages.es]
    title = "El Blog de Vía Código"
    weight = 1
    [languages.es.params]
    languageCode = "es-PE"
    description = "Programando el futuro"
    ErrorMessage404 = "¡Esta página no existe!"
   
    linkedin = "https://linkedin.com/whoever"
  [languages.en]
    title = "Blog: Via Codigo"
    weight = 2
    [languages.en.params]
    languageCode = "en-US"
    description = "Programming the future"
    ErrorMessage404 = "Page not found!"
    [[languages.en.menu.main]]
    name = "Blog"
    url = "/"
    weight = 1
    [[languages.en.menu.main]]
    name = "Web"
    url = "https://viacodigo.com/"
    weight = 3
    [[languages.en.menu.main]]
    name = "Contact"
    url = "https://viacodigo.com/involucrate/"
    weight = 4
    [[languages.en.menu.main]]
    name = "Español"
    url = "https://blog.viacodigo.com/"
    weight = 5
   
[Author]
    name = "Vía Código"
    profile = "https://viacodigo.com"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Vía Código"
    
    github = "https://github.com/Via-Codigo"
    linkedin = "https://www.linkedin.com/company/via-codigo/"
    twitter = "https://twitter.com/ViaCodigo"
    facebook = "https://www.facebook.com/viacodigoperu/"
    
    email = "info@viacodigo.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true

    shareLinkedIn = true
    dateFormat = "Mon, Jan 2, 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

    

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Categorías"
#     url = "#"
#     weight = 2

[[menu.main]]
    name = "Web"
    url = "https://viacodigo.com/"
    weight = 3

[[menu.main]]
    name = "Contacto"
    url = "https://viacodigo.com/involucrate/"
    weight = 4
[[menu.main]]
    name = "English"
    url = "https://blog.viacodigo.com/en/"
    weight = 5

